Update dynawo and dynaflow to 1.5.0
powsybl/java-dynawo-docker pull request #6
Opened 2023-10-09 15:59 UTC by flo-dup

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines

**Does this PR already have an issue describing the problem?**

No

**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

dynawo 1.4.0
dynaflow 1.4.0

**What is the new behavior (if this is a feature change)?**
dynawo 1.5.0
dynaflow 1.5.0

**Does this PR introduce a breaking change or deprecate an API?**

No

2023-10-11 19:01 UTC, geofjamg approved these changes

2023-10-11 19:03 UTC, geofjamg requested changes
You forgot to increase the image version

2023-11-02 11:51 UTC, thangqp reviewed
tags: "2.1.0" as in gridsuite/java-simulator ?

2023-11-02 12:05 UTC, geofjamg commented
> tags: "2.1.0" as in gridsuite/java-simulator ?

Yes

2023-11-02 16:25 UTC, geofjamg approved these changes

2023-11-02 16:48 UTC, merged